---
title: "Tables"
---


# Let's build some tables!

```{r installations, eval=F, echo=F, include=F, warning=F}
# install.packages(c("tidyverse", "here"))
# install.packages("devtools")
# our package
devtools::install_github("jravilab/iprscanr")
# some table packages
install.packages(c("fontawesome", "rmarkdown", "kableExtra", "gt", "DT"),
                 dependencies = T)
# try out shiny/flex dashboard
# install.packages(c("shiny", "shinydashboard", "flexdashboard"),
# dependencies = T)
```

```{r load_libs, eval=T, echo=T, warning=F, include=FALSE}
library(tidyverse)
library(here)
library(fontawesome)
# our data package
library(iprscanr)
# table packages
library(rmarkdown)
library(kableExtra)
library(DT)
library(gt)
# to try shiny/flex dashboard
# library(shiny); library(shinydashboard); library(flexdashboard)
```

## Explore your IPR results here

```{r load_data, eval=T, echo=T, warning=F, include=F}

# Read in IPRscan results for 1 protein
# infile_ipr <- paste0(system.file(package="iprscanr"),
#                      "/extdata/ex-out-CAA75348.tsv")

# Read in IPRscan results for 42 proteins
infile_ipr <- paste0(system.file(package="iprscanr"),
                     "/extdata/ex-42-out/joined.tsv")

ipr_combnd <- read_tsv(infile_ipr, col_names=T)

ipr_colnames <- c("AccNum", "SeqMD5Digest", "SLength", "Analysis",
                  "DB.ID", "SignDesc", "StartLoc", "StopLoc", "Score",
                  "Status", "RunDate", "IPRAcc", "IPRDesc")
colnames(ipr_combnd) <- ipr_colnames

ipr_combnd <- ipr_combnd |>
  select(AccNum, Analysis, DB.ID, SignDesc,
         StartLoc, StopLoc, SLength,
         IPRAcc, IPRDesc) |>
  arrange(AccNum, StartLoc)

ipr_combnd$AccNum <- ipr_combnd$AccNum |>
  str_replace(pattern = ".1_.*", replacement = "")
```

## w/ knitr
```{r knitr}
knitr::kable(head(ipr_combnd), format='html')

```

## w/ rmarkdown
```{r rmarkdown}
paged_table(ipr_combnd)
```

## w/ kableExtra 
```{r kableExtra, eval=TRUE, echo=T, warning=FALSE}

ipr_combnd |>
  head() |>
  kable(caption = "Table 1. Annotate with kableExtra") |>
  kable_styling(c("striped", "hover", "condensed"), full_width = F,
                position = "left") |>
  add_header_above(c("protein"=1, "domains" = 8)) |>
  column_spec(1, bold = T) |>
  row_spec(0, italic = T)

```

You can search, sort, and query the table interactively.

## w/ DT, datatable
```{r datatable, eval=TRUE, echo=T, warning=F}
ipr_combnd |>
  head() |> 
  datatable(fillContainer=FALSE,
            options=list(pageLength=8))
```
### adding extensions
You can now show/hide specific columns using the `Column visibility` button.

```{r datatable2, eval=T, echo=T, warning=F}

DT::datatable(ipr_combnd,
              extensions = c('Buttons', 'FixedColumns',
                             'RowReorder', 'RowGroup'),
              options = list(
                pageLength = 5,
                dom = 'Bfrtip',
                buttons = I('colvis'),
                buttons=list(list(extend = 'colvis', columns = c(5:9))),
                fixedColumns = list(leftColumns = 2),
                fixedHeader = TRUE,
                rowReorder = TRUE, order = list(c(0, 'asc')),
                scrollX = TRUE,
                rowGroup = list(dataSrc = 1),
                lengthMenu = c(10, 25, 100)
              ))

```

## w/ gt
```{r gt}
ipr_combnd |>
  head() |> 
  gt()

ipr_gt <- ipr_combnd |>
  group_by(AccNum) |> 
  gt() |> 
  tab_header(title=md("IPRScan Results"), subtitle="using GT") |>
  tab_source_note(md("More information on the [GT package](https://gt.rstudio.com/index.html).")) |> 
  cols_align(align="right", columns=TRUE) |> 
  tab_spanner(label="Protein", columns=matches("AccNum")) |> 
  tab_spanner(label="Domains", columns=matches("Analysis|DB.ID|SignDesc")) |> 
  tab_spanner(label="DomLoc", columns=matches("Loc|Length")) |>
  tab_spanner(label="IPR", columns=matches("IPR")) |>
  tab_options(
    # Headings; Titles
		heading.background.color="#3C5488",
		heading.border.bottom.color="#989898",
		heading.title.font.size="12px",
		heading.subtitle.font.size="11px",
		# Column labels
		column_labels.background.color="#4DBBD5", #B09C85FF
		column_labels.font.size="12px",
		# Stubs
		stub.background.color="#4DBBD5", #B09C85FF
		stub.border.style="dashed",
		stub.border.color="#989898",
		stub.border.width="1px",
		# Row groups
		row_group.background.color="coral3", #FFEFDB80
		row_group.border.top.color="#989898",
		row_group.border.bottom.style="none",
		row_group.font.size="12px",
		# Summary rows
		summary_row.border.color="#989898",
		# summary_row.background.color="#FFEBEE",
		# grand_summary_row.background.color="#FFFFFF",
		# Table
		table.font.color="#323232",
		table_body.hlines.color="#989898",
		table_body.border.top.color="#989898",
		table.font.size="10px",
		table.width="80%")
ipr_gt
```
